package br.com.souto;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import br.com.souto.Analytics;

import static org.junit.Assert.*;

public class AnalyticsTest {
    @Test public void emptyTest() {
        Analytics classUnderTest = new Analytics();
        assertNotNull("app should have a greeting", "emptyTest");
    }
}
