package br.com.souto;

import java.io.IOException;
import java.util.List;

import br.com.souto.analytics.SalesAnalysis;
import br.com.souto.container.RegistersContainer;
import br.com.souto.repository.SalesData;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Analytics {
	public static void main(String[] args) {
		List<RegistersContainer> registersContainersList;
        try {
			registersContainersList = new SalesData().getRegistersContainers();
			System.out.println(registersContainersList);
			System.out.println(new SalesAnalysis().process(registersContainersList));
			registersContainersList.forEach((registerContainer) -> System.out.println(registerContainer.process()));
		} catch (IOException e) {
			System.out.println("Erro ao ler arquivo de entrada");
		}
    }
}
