package br.com.souto;

import java.io.IOException;
import java.util.List;
import java.util.Map;

import br.com.souto.model.Registry;
import br.com.souto.repository.RegistersIds;
import br.com.souto.repository.SalesData;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Analytics {
	public static void main(String[] args) {
		Map<RegistersIds, List<Registry>> registers;
        try {
			registers = new SalesData().getRegisters();
			System.out.println(registers);
		} catch (IOException e) {
			System.out.println("Erro ao ler arquivo de entrada");
		}
    }
}
