package br.com.souto;

import java.io.IOException;

import br.com.souto.io.SalesData;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Analytics {

    public static void main(String[] args) {
        try {
			new SalesData().get();
		} catch (IOException e) {
			System.out.println("Erro ao ler arquivo de entrada");
		}
    }
}
