package br.com.souto.analytics;

import java.util.List;

import br.com.souto.processor.RegistersProcessor;

public class SalesAnalysis {
	
	String reports = new String();
	
	public String process(List<RegistersProcessor> registersProcessorsList) {
		registersProcessorsList.forEach((registerProcessor) -> reports += registerProcessor.process() + "\n");
		return reports;
	}
	
	/* Strategy Design Pattern
	 * Returns the report generated by the dowcasted
	 * RegisterProcessor subclass process method
	 */
	public static String process(RegistersProcessor registersProcessor) {
		return registersProcessor.process();
	}

}
