package br.com.souto.analytics;

import java.util.List;

import br.com.souto.container.RegistersContainer;

public class SalesAnalysis {
	
	String reports = new String();
	
	public String process(List<RegistersContainer> registersContainersList) {
		registersContainersList.forEach((registerContainer) -> reports += registerContainer.process() + "\n");
		return reports;
	}
	
	/* Strategy Design Pattern
	 * Returns the report generated by the dowcasted
	 * RegisterContainer subclass process method
	 */
	public static String process(RegistersContainer registersContainer) {
		return registersContainer.process();
	}

}
